# Generated by Django 5.2.11 on 2026-02-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
