# Generated by Django 5.2.11 on 2026-02-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='subject',
            field=models.CharField(max_length=150),
        ),
    ]
