# Generated by Django 5.2.11 on 2026-02-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_personalschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalschool',
            name='number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
